# Generated by Django 6.0.2 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('promo_price', models.CharField(blank=True, max_length=50, null=True)),
                ('regular_price', models.CharField(blank=True, max_length=50, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('specs', models.TextField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
