# Generated by Django 6.0.2 on 2026-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='screen_diagonal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
